### ISSUE TITLE
How do you install on Windows 10 linux subsystem?

### ISSUE THREAD

**Issue by delebash** [FORTH-ModelBasedTracker/MocapNET#14]
Ubuntu installs successfully.

Steps

1) git clone  https://github.com/FORTH-ModelBasedTracker/MocapNET.git

2) sudo apt-get update

3) sudo apt-get install build-essential cmake libopencv-dev libjpeg-dev libpng-dev libglew-dev

4) run ./initialize.sh

The problem I am running into is with step 4.  

It gets to
 [ 21%] Building CXX object src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/__/MocapNETLib/visualization.cpp

and then reports many errors first error

o/home/me/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp: In function ‘int visualizeNSDM(cv::Mat&, std::vector<float>, unsigned int, unsigned int, unsigned int, unsigned int)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:116:1: warning: no return statement in function returning non-void [-Wreturn-type]
  116 | }
      | ^

Any ideas on how to fix this?

**Comment by AmmarkoV** [comment]
Hello, 
can you please provide the full output of cmake ? 
the warning about line 116 is not the problem

**Comment by delebash** [comment]
Here it is.  Thanks

[ 21%] Building CXX object src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/__/MocapNETLib/visualization.cpp.o/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp: In function ‘int visualizeNSDM(cv::Mat&, std::vector<float>, unsigned int, unsigned int, unsigned int, unsigned int)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:116:1: warning: no return statement in function returning non-void [-Wreturn-type]
  116 | }
      | ^
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp: In function ‘int visualizeNSDMAsBar(cv::Mat&, std::vector<float>, unsigned int, unsigned int, unsigned int, unsigned int)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:182:1: warning: no return statement in function returning non-void [-Wreturn-type]
  182 | }
      | ^
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp: In function ‘int drawFloorFromPrimitives(cv::Mat&, float, float, float, unsigned int, unsigned int, unsigned int)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:246:1: warning: no return statement in function returning non-void [-Wreturn-type]
  246 | }
      | ^
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp: In function ‘int visualizeCameraEdges(const char*, cv::Mat&)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:550:30: error: ‘CV_BGR2GRAY’ was not declared in this scope
  550 |     cv::cvtColor(img, edges, CV_BGR2GRAY);
      |                              ^~~~~~~~~~~
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp: In function ‘int visualizeCameraFeatures(const char*, cv::Mat&)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:586:1: warning: no return statement in function returning non-void [-Wreturn-type]
  586 | }
      | ^
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp: In function ‘int visualizeInput2DSkeletonFromCOCOStruct(cv::Mat&, skeletonCOCO*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:1095:1: warning: no return statement in function returning non-void [-Wreturn-type]
 1095 | }
      | ^
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp: In function ‘int visualizeInput(const char*, unsigned int, unsigned int, const char*, skeletonCOCO*, unsigned int, unsigned int, std::vector<float>, std::vector<std::vector<float> >, std::vector<std::vector<float> >, std::vector<std::vector<float> >, unsigned int)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:1127:36: error: ‘CV_LOAD_IMAGE_COLOR’ was not declared in this scope
 1127 |      image = imread(finalFilename, CV_LOAD_IMAGE_COLOR);   // Read the file
      |                                    ^~~~~~~~~~~~~~~~~~~
make[2]: *** [src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/build.make:414: src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/__/MocapNETLib/visualization.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:299: src/MocapNET1/MocapNETFromJSON/CMakeFiles/MocapNETJSON.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by delebash** [comment]
I also ran your HellloWorld test project and it compiled successfully

**Comment by AmmarkoV** [comment]
Hello so reading the cmake output notice that the errors are actually :

/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:550:30: error: ‘CV_BGR2GRAY’ was not declared in this scope

/home/delebash/MocapNET/src/MocapNET1/MocapNETLib/visualization.cpp:1127:36: error: ‘CV_LOAD_IMAGE_COLOR’ was not declared in this scope

Compilation warnings are just warnings but they don't stop the compilation, in any case I fixed them :D so they wont appear any more..

Now your error is that the OpenCV defines are not being recognized, depending on OpenCV version  the symbol "CV_LOAD_IMAGE_COLOR" has been replaced with "cv::IMREAD_COLOR" so I changed to the newer OpenCV defines
https://github.com/FORTH-ModelBasedTracker/MocapNET/commit/b07331500baa8b4fef29482cddc9f27d8def41b8

You should pull and see if compilation will work now!

**Comment by delebash** [comment]
Thank you for tge quick response,  I am still getting a couple of errors but the original as you noted has been fixed.  Thank you!

[ 72%] Building CXX object src/Webcam/CMakeFiles/OpenCVTest.dir/webcam.cpp.o
/home/delebash/MocapNET/src/Webcam/webcam.cpp: In function ‘int main(int, char**)’:
/home/delebash/MocapNET/src/Webcam/webcam.cpp:30:21: error: ‘CV_CAP_PROP_FRAME_WIDTH’ was not declared in this scope
   30 |             cap.set(CV_CAP_PROP_FRAME_WIDTH,640);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~
/home/delebash/MocapNET/src/Webcam/webcam.cpp:31:21: error: ‘CV_CAP_PROP_FRAME_HEIGHT’ was not declared in this scope
   31 |             cap.set(CV_CAP_PROP_FRAME_HEIGHT,480);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/Webcam/CMakeFiles/OpenCVTest.dir/build.make:63: src/Webcam/CMakeFiles/OpenCVTest.dir/webcam.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:434: src/Webcam/CMakeFiles/OpenCVTest.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by AmmarkoV** [comment]
It is the same CV defines issue, just at a different part of the code, this time the part where I use OpenCV to grab a feed from the webcam..
I think I corrected it, so if you could try pulling and recompiling..
I think we are closing in on fixing this :)

**Comment by delebash** [comment]
Thanks.  I think this should be the last one same prob

/home/delebash/MocapNET/src/MocapNET1/MocapNETLiveWebcamDemo/utilities.cpp: In function ‘std::vector<cv::Point_<float> > dj_getNeuralNetworkDetectionsForColorImage(cv::Mat, cv::Mat, std::vector<cv::Mat>, float, unsigned int, int, int, unsigned int, unsigned int, int)’:
/home/delebash/MocapNET/src/MocapNET1/MocapNETLiveWebcamDemo/utilities.cpp:338:36: error: ‘CV_MINMAX’ was not declared in this scope; did you mean ‘CV_MMX’?
  338 |     cv::normalize(bg,bgNorm,0,255, CV_MINMAX, CV_8UC1);

**Comment by AmmarkoV** [comment]
Ok try pulling/making once more!

**Comment by delebash** [comment]
All fixed thank you very much and thanks for the program!

**Comment by AmmarkoV** [comment]
Glad it works :) , thank you too for reporting the issue with the OpenCV defines to future proof the code!
Also I have a very big improvement in pose estimation accuracy ready and pending review so hopefully in the very near future 3D pose estimation will work better..!

**Comment by delebash** [comment]
Sure.  Awesome looking forward to the update!
